site_name: Pi-thon 

theme: 
  name: readthedocs

markdown_extensions: 
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav: 
  - Home: index.md
  - Getting Started: user_guide.md
  - Mathematics: mathematics.md
  - Implementation: implementation.md
  - Testing: test.md
  - Benchmarks: benchmark.md